// Command gen-ts generates the TypeScript API model (web/src/types.gen.ts)
// from the Go types that the HTTP API actually serializes, using reflection
// over their json struct tags. Run via `go generate ./...`.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/JohanLindvall/Mediator/internal/library"
	"github.com/JohanLindvall/Mediator/internal/server"
	"github.com/JohanLindvall/Mediator/internal/state"
)

var kindType = reflect.TypeOf(library.Kind(""))

// rootTypes lists every payload type exposed by the API, in output order.
// Struct types referenced by these are resolved by name and must be included.
var rootTypes = []any{
	library.Item{},
	library.AudioTrack{},
	library.Flags{},
	library.Counts{},
	library.Result{},
	library.Event{},
	library.Album{},
	library.Artist{},
	library.Genre{},
	library.Series{},
	library.Season{},
	library.Subtitle{},
	state.Position{},
	server.Build{},
	server.Capabilities{},
	server.ListQueryParams{},
	server.AlbumsResponse{},
	server.ArtistsResponse{},
	server.GenresResponse{},
	server.SeriesResponse{},
	server.PlayResponse{},
	server.LikeUpdate{},
	server.LikeResponse{},
	server.AlbumDetailResponse{},
	server.TracksResponse{},
	server.SubtitlesResponse{},
	server.KeyframeResponse{},
	server.CropResponse{},
	server.LinkRequest{},
	server.LinkResponse{},
	server.InfoResponse{},
	server.PrefsResponse{},
	server.PrefsUpdate{},
	server.ConvertProgress{},
	server.PositionsResponse{},
	server.PositionUpdate{},
	server.FlagUpdate{},
	server.FlagsResponse{},
	server.SpriteLayout{},
	server.RendererInfo{},
	server.RenderersResponse{},
	server.CastStatus{},
	server.CastControl{},
}

// constValues are Go values emitted as TypeScript constants: conventions the
// client has to agree with the server on exactly, where a second definition
// in the frontend would be a second thing to keep in step.
var constValues = []struct {
	name string
	typ  string
	val  any
}{
	{"SPRITE", "SpriteLayout", server.Sprite},
}

func main() {
	out := flag.String("out", "web/src/types.gen.ts", "output file")
	flag.Parse()

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-ts from the Go API types. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go generate ./...\n\n")

	var kinds []string
	for _, k := range library.AllKinds {
		kinds = append(kinds, fmt.Sprintf("%q", string(k)))
	}
	fmt.Fprintf(&b, "export type Kind = %s;\n", strings.Join(kinds, " | "))

	known := map[string]bool{}
	for _, v := range rootTypes {
		known[reflect.TypeOf(v).Name()] = true
	}
	for _, v := range rootTypes {
		emitInterface(&b, reflect.TypeOf(v), known)
	}
	for _, c := range constValues {
		// The json encoding of the value is a TypeScript object literal, and
		// it uses the very json tags the interface was emitted from.
		lit, err := json.Marshal(c.val)
		if err != nil {
			fmt.Fprintln(os.Stderr, "gen-ts:", err)
			os.Exit(1)
		}
		fmt.Fprintf(&b, "\nexport const %s: %s = %s;\n", c.name, c.typ, lit)
	}

	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gen-ts:", err)
		os.Exit(1)
	}
	fmt.Printf("gen-ts: wrote %s (%d types)\n", *out, len(rootTypes))
}

func emitInterface(b *bytes.Buffer, t reflect.Type, known map[string]bool) {
	fmt.Fprintf(b, "\nexport interface %s {\n", t.Name())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" { // unexported
			continue
		}
		name, opts, ok := jsonName(f)
		if !ok {
			continue
		}
		opt := ""
		if strings.Contains(opts, "omitempty") {
			opt = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", name, opt, tsType(f.Type, known))
	}
	b.WriteString("}\n")
}

func jsonName(f reflect.StructField) (name, opts string, ok bool) {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", "", false
	}
	name, opts, _ = strings.Cut(tag, ",")
	if name == "" {
		name = f.Name
	}
	return name, opts, true
}

func tsType(t reflect.Type, known map[string]bool) string {
	if t == kindType {
		return "Kind"
	}
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem(), known)
	case reflect.Slice, reflect.Array:
		return tsType(t.Elem(), known) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(t.Key(), known), tsType(t.Elem(), known))
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Struct:
		if !known[t.Name()] {
			panic(fmt.Sprintf("type %s is referenced by the API but not listed in rootTypes", t))
		}
		return t.Name()
	default:
		panic(fmt.Sprintf("unsupported kind %s (%s)", t.Kind(), t))
	}
}
