package server

import (
	"github.com/JohanLindvall/Mediator/internal/library"
	"github.com/JohanLindvall/Mediator/internal/state"
)

// Named API payload types. These (plus the library/state types they refer to)
// are the source of truth for the TypeScript model generated by cmd/gen-ts.

// ListQueryParams documents the query parameters of GET /api/library
// (also reused, minus kind/offset/limit, by GET /api/albums, and in full —
// minus offset/limit — by the m3u export at GET /api/playlist.m3u).
type ListQueryParams struct {
	Kind library.Kind `json:"kind,omitempty"`
	// Watch narrows a listing by how far it has been got through:
	// "started" (begun, unfinished) or "done" (watched through).
	Watch string `json:"watch,omitempty"`
	// Played=1 keeps only what has been played at all: the popularity view.
	Played string `json:"played,omitempty"`
	Q      string `json:"q,omitempty"`
	Artist string `json:"artist,omitempty"`
	// Genre narrows the albums endpoint to one genre, as artist does to one
	// performer.
	Genre string `json:"genre,omitempty"`
	// Series and Season narrow a listing to one show, and to one season of
	// it — which is what a season card opens.
	Series string `json:"series,omitempty"`
	Season string `json:"season,omitempty"` // with Series: one season of that show
	// Sort is the view's own key. Items: "name" | "mtime" | "size" | "added" |
	// "duration" | "popular" | "pixels" | "bitrate" | "episode" | "random";
	// the grouped views take theirs (year, artist, genre, tracks, albums,
	// episodes, seasons …) and "similarity" where near is set.
	Sort  string `json:"sort,omitempty"`
	Order string `json:"order,omitempty"` // "asc" | "desc"
	// Seed picks which shuffle sort=random deals. Choose it once per query
	// and send it with every page: a new seed reshuffles, which would repeat
	// and skip items across page boundaries.
	Seed   int64  `json:"seed,omitempty"`
	Hidden string `json:"hidden,omitempty"` // "exclude" (default) | "include" | "only"
	Fav    string `json:"fav,omitempty"`    // "1": only items marked favourite
	Offset int    `json:"offset,omitempty"`
	Limit  int    `json:"limit,omitempty"`
}

// AlbumsResponse is the body of GET /api/albums.
type AlbumsResponse struct {
	Albums  []*library.Album `json:"albums"`
	Version int64            `json:"version"`
	// Matching is what the chips show while a search is on, as on the
	// listing: this view fetches no items, so without it the chips above an
	// album search would still be counting the whole library.
	Matching *library.Counts `json:"matching,omitempty"`
}

// ArtistsResponse is the body of GET /api/artists.
type ArtistsResponse struct {
	Artists  []*library.Artist `json:"artists"`
	Version  int64             `json:"version"`
	Matching *library.Counts   `json:"matching,omitempty"`
}

// SeriesResponse is the body of GET /api/series. The seasons travel inside
// each show rather than behind an endpoint of their own: a series has a
// handful, they are wanted the moment one is opened, and a second request to
// learn "Season 1, Season 2" would be a request to learn almost nothing.
type SeriesResponse struct {
	Series   []*library.Series `json:"series"`
	Version  int64             `json:"version"`
	Matching *library.Counts   `json:"matching,omitempty"`
}

// PlayResponse is the body of POST /api/plays/{id}: the new count.
// LikeUpdate is the owner's verdict on one item: 1, -1, or 0 to withdraw it.
type LikeUpdate struct {
	Like int `json:"like"`
}

// LikeResponse is the verdict as stored.
type LikeResponse struct {
	Like int `json:"like"`
}

type PlayResponse struct {
	Plays int `json:"plays"`
}

// GenresResponse is the body of GET /api/genres.
type GenresResponse struct {
	Genres   []*library.Genre `json:"genres"`
	Version  int64            `json:"version"`
	Matching *library.Counts  `json:"matching,omitempty"`
}

// AlbumDetailResponse is the body of GET /api/albums/{id}.
type AlbumDetailResponse struct {
	Album  *library.Album `json:"album"`
	Tracks []library.Item `json:"tracks"`
}

// TracksResponse is the tracks behind a view, in the order a queue plays
// them (handleTracks). Truncated says the view holds more than a queue takes.
type TracksResponse struct {
	Tracks    []library.Item `json:"tracks"`
	Truncated bool           `json:"truncated,omitempty"`
}

// SubtitlesResponse is the body of GET /api/subs/{id}: the external
// subtitle files found next to a video, in menu order.
type SubtitlesResponse struct {
	Subs []library.Subtitle `json:"subs"`
}

// KeyframeResponse is the body of GET /api/keyframe/{id}?t=: the time a
// transcode that copies the video stream would really start at, were it
// asked to seek to t. It is at or before t, by up to the spacing between two
// keyframes — ten seconds is unremarkable.
type KeyframeResponse struct {
	Start float64 `json:"start"`
}

// InfoResponse is the body of GET /api/info: what the client needs to know
// about the server it is talking to before it asks for anything else.
type InfoResponse struct {
	// ThumbEpoch identifies the store the thumbnails come from. The client
	// puts it in every thumbnail and sprite URL, because those are served
	// immutable for a year and are versioned otherwise only by the source
	// file's mtime — so without it, deleting the database changes nothing a
	// browser can see and it goes on showing images the server has forgotten.
	ThumbEpoch string `json:"thumbEpoch"`
	// Content is what this caller may see, when it is not everything:
	// "videos", "images", "music", in that order. Absent means the whole
	// library, which is what a request with no `X-Media-Content` header
	// gets. The client uses it to leave out the views it has no business
	// offering; the server does not rely on it having done so.
	Content []string `json:"content,omitempty"`
	// StreamToken is what makes a media URL carry its own permission, so
	// that something fetching one without a browser behind it — an AirPlay
	// receiver above all — is not refused by whatever guards this
	// deployment. The page puts it in the media URLs it builds. Empty when
	// nothing can be signed. See sign.go.
	StreamToken string `json:"streamToken,omitempty"`
	// Confined says this caller sees only part of the library
	// (`X-Allowed-Paths`). The page leaves the preferences out when it is
	// set, those naming the directories the library is rooted at — which a
	// caller allowed one branch has no business learning. As with Content,
	// the page doing so is a courtesy; handlePrefs is the guarantee.
	Confined bool `json:"confined,omitempty"`
	// Build is what is running, and Capabilities what it found it could do
	// here. Neither is readable from the outside otherwise: a binary that
	// has been rebuilt and not restarted looks exactly like one that has,
	// and hardware conversion either happens or does not, silently.
	Build        Build        `json:"build"`
	Capabilities Capabilities `json:"capabilities"`
	// StreamExpires is when that token stops working, in unix seconds, so a
	// page left open overnight can fetch another before it matters.
	StreamExpires int64 `json:"streamExpires,omitempty"`
}

// CropResponse is the body of GET /api/crop/{id}: where the picture actually
// is inside the file's frame, when the file carries black borders of its own.
// A zero box means there is nothing to trim, which is the ordinary case.
type CropResponse struct {
	X int `json:"x,omitempty"`
	Y int `json:"y,omitempty"`
	W int `json:"w,omitempty"`
	H int `json:"h,omitempty"`
	// FrameW and FrameH are what the box is a part of, so a client can tell
	// how much is being given back without measuring the element first.
	FrameW int `json:"frameW,omitempty"`
	FrameH int `json:"frameH,omitempty"`
}

// PositionsResponse is the body of GET /api/state.
type PositionsResponse struct {
	Positions map[string]state.Position `json:"positions"`
}

// FlagUpdate is the body of PUT /api/flags/{id} and of PUT /api/flags, where
// ids names the items to change. A flag left out is left as it is, so the two
// judgements can be set independently of one another.
type FlagUpdate struct {
	IDs       []string `json:"ids,omitempty"` // batch form only
	Hidden    *bool    `json:"hidden,omitempty"`
	Favourite *bool    `json:"favourite,omitempty"`
	// Rotation is quarter turns clockwise, 0-3, for footage shot sideways.
	Rotation *int `json:"rotation,omitempty"`
	// NoCrop keeps a file's black borders, which are otherwise trimmed
	// wherever they are found.
	NoCrop *bool `json:"nocrop,omitempty"`
}

// FlagsResponse is the body of the flag endpoints: the flags every item the
// request named now has, by item ID.
type FlagsResponse struct {
	Flags map[string]library.Flags `json:"flags"`
}

// SpriteLayout is the fixed geometry of the scrub sheet served by
// GET /api/sprite/{id}. There is no metadata endpoint for it: the client
// takes these numbers from the generated model and derives frame i's
// timestamp as duration*(i+0.5)/frames, which is where it was sampled.
type SpriteLayout struct {
	Frames        int `json:"frames"`
	Cols          int `json:"cols"`
	Rows          int `json:"rows"`
	FrameWidth    int `json:"frameWidth"`    // pixels; the height follows the aspect ratio
	MinDurationMs int `json:"minDurationMs"` // shorter videos have no sheet (404)
}

// Sprite is that geometry, generated into the TypeScript model as a constant
// so both sides read one definition of the convention.
var Sprite = SpriteLayout{
	Frames:        spriteFrames,
	Cols:          spriteCols,
	Rows:          spriteRows,
	FrameWidth:    spriteFrameWidth,
	MinDurationMs: spriteMinDurationMs,
}

// PositionUpdate is the body of PUT /api/state/{id}.
type PositionUpdate struct {
	Time     float64 `json:"t"`
	Duration float64 `json:"d"`
}

// PrefsResponse is the server's mutable configuration.
type PrefsResponse struct {
	// Roots are the directories being indexed, absolute and in the order
	// they were given.
	Roots []string `json:"roots"`
	// Persisted is false when there is no database to write them to, so a
	// change lasts the run and the startup arguments come back afterwards.
	// The dialog says so rather than letting the setting look permanent.
	Persisted bool `json:"persisted"`
	// Editable is false on a server started with -lock. The dialog then
	// shows what is indexed and offers nothing to change it, rather than
	// offering controls whose every use is refused.
	Editable bool `json:"editable"`
}

// PrefsUpdate replaces the set of directories to index.
type PrefsUpdate struct {
	Roots []string `json:"roots"`
}

// ConvertProgress says how far a conversion of one item has reached.
type ConvertProgress struct {
	// Active is false when nothing is being converted for this item, which
	// is also the answer while it plays straight from the file.
	Active bool `json:"active"`
	// Percent is 0..100 of the work, not of the watching.
	Percent int `json:"percent"`
	// Kind is what is being done: "rewrap" moves the streams into a
	// container the browser opens, "convert" re-encodes what it cannot play.
	Kind string `json:"kind,omitempty"`
}

// RendererInfo is one device on the network that will play what it is sent.
type RendererInfo struct {
	// ID is derived from the device's own identity rather than its address,
	// so a chosen receiver survives a restart at either end.
	ID string `json:"id"`
	// Name is what the set is called on the network, which is what its
	// owner named it.
	Name string `json:"name"`
	// Volume says whether it exposes a volume to set. Some renderers play
	// what they are given and are turned up with their own remote.
	Volume bool `json:"volume,omitempty"`
}

// RenderersResponse lists what answered the last search.
type RenderersResponse struct {
	Renderers []RendererInfo `json:"renderers"`
}

// CastStatus is where a renderer says it has got to. Seconds throughout,
// matching the media element the rest of the client is written against.
type CastStatus struct {
	// State is the transport's own word: PLAYING, PAUSED_PLAYBACK, STOPPED,
	// TRANSITIONING or NO_MEDIA_PRESENT.
	State string `json:"state"`
	// Position and Duration are 0 where the set will not say — which it
	// legitimately does before it has opened the file.
	Position float64 `json:"position,omitempty"`
	Duration float64 `json:"duration,omitempty"`
	// URI is what it is playing, which is how a client tells that the set is
	// still showing what it sent rather than something started elsewhere.
	URI string `json:"uri,omitempty"`
}

// CastControl drives a renderer that is already playing.
type CastControl struct {
	// Action is play, pause, stop, seek or volume.
	Action string `json:"action"`
	// Seconds is where to seek to, for the seek action.
	Seconds float64 `json:"seconds,omitempty"`
	// Volume is 0..100, for the volume action.
	Volume int `json:"volume,omitempty"`
}

// LinkRequest asks for a shortlink to a piece of app state.
type LinkRequest struct {
	// Target is the URL fragment that describes where the link should land —
	// the view, and the one item on top of it where there is one. It is
	// stored as given: what a view is called is the frontend's business.
	Target string `json:"target"`
}

// LinkResponse is the shortlink that was minted, or the one that already
// existed for this target.
type LinkResponse struct {
	Code string `json:"code"`
	// Path is where the code is answered, relative to the site root, so the
	// page can make it absolute against whatever host it was opened on —
	// which is the only one that knows which face of the library this is.
	Path string `json:"path"`
}
