// Code generated by cmd/gen-ts from the Go API types. DO NOT EDIT.
// Regenerate with: go generate ./...

export type Kind = "video" | "image" | "audio" | "playlist";

export interface Item {
  id: string;
  name: string;
  path: string;
  kind: Kind;
  size: number;
  mtime: number;
  added?: number;
  duration?: number;
  title?: string;
  artist?: string;
  album?: string;
  genre?: string;
  track?: number;
  year?: number;
  tracks?: AudioTrack[];
  vcodec?: string;
  acodec?: string;
  reencode?: boolean;
  width?: number;
  height?: number;
  fps?: number;
  series?: string;
  season?: number;
  episode?: number;
  plays?: number;
  like?: number;
  affinity?: number;
  akin?: string;
  spoken?: boolean;
  rotation?: number;
  nocrop?: boolean;
  hidden?: boolean;
  favourite?: boolean;
}

export interface AudioTrack {
  index: number;
  codec?: string;
  lang?: string;
  title?: string;
  channels?: number;
  default?: boolean;
  comment?: boolean;
}

export interface Flags {
  hidden?: boolean;
  favourite?: boolean;
  rotation?: number;
  nocrop?: boolean;
}

export interface Counts {
  video: number;
  image: number;
  audio: number;
  playlist: number;
  albums: number;
  audiobooks: number;
  artists: number;
  genres: number;
  series: number;
  started: number;
  watched: number;
  played: number;
  total: number;
}

export interface Result {
  items: Item[];
  total: number;
  version: number;
  counts: Counts;
  matching?: Counts;
}

export interface Event {
  version: number;
  counts: Counts;
}

export interface Album {
  id: string;
  name: string;
  artist?: string;
  source: string;
  tracks: number;
  coverId?: string;
  genre?: string;
  genres?: string[];
  year?: number;
  size: number;
  duration?: number;
  plays?: number;
  likes?: number;
  mtime: number;
  spoken?: boolean;
  similarity?: number;
}

export interface Artist {
  id: string;
  name: string;
  albums: number;
  tracks: number;
  coverId?: string;
  genre?: string;
  fromYear?: number;
  toYear?: number;
  size: number;
  duration?: number;
  plays?: number;
  likes?: number;
  mtime: number;
  similarity?: number;
}

export interface Genre {
  id: string;
  name: string;
  artists: number;
  albums: number;
  tracks: number;
  coverId?: string;
  fromYear?: number;
  toYear?: number;
  size: number;
  duration?: number;
  plays?: number;
  likes?: number;
  mtime: number;
}

export interface Series {
  id: string;
  name: string;
  seasons: Season[];
  episodes: number;
  coverId?: string;
  size: number;
  duration?: number;
  plays?: number;
  likes?: number;
  mtime: number;
}

export interface Season {
  season: number;
  episodes: number;
  coverId?: string;
  size: number;
  duration?: number;
  plays?: number;
  likes?: number;
  mtime: number;
}

export interface Subtitle {
  index: number;
  label: string;
  lang?: string;
}

export interface Position {
  t: number;
  d: number;
  u: number;
  p?: number;
  lp?: number;
  l?: number;
}

export interface Build {
  version: string;
  commit?: string;
  time?: string;
  modified?: boolean;
  go: string;
  os: string;
  arch: string;
}

export interface Capabilities {
  ffmpeg: boolean;
  ffprobe: boolean;
  hardware?: string;
  device?: string;
  database: boolean;
  loopback: boolean;
}

export interface ListQueryParams {
  kind?: Kind;
  watch?: string;
  played?: string;
  q?: string;
  artist?: string;
  genre?: string;
  series?: string;
  season?: string;
  sort?: string;
  order?: string;
  seed?: number;
  hidden?: string;
  fav?: string;
  offset?: number;
  limit?: number;
}

export interface AlbumsResponse {
  albums: Album[];
  version: number;
  matching?: Counts;
}

export interface ArtistsResponse {
  artists: Artist[];
  version: number;
  matching?: Counts;
}

export interface GenresResponse {
  genres: Genre[];
  version: number;
  matching?: Counts;
}

export interface SeriesResponse {
  series: Series[];
  version: number;
  matching?: Counts;
}

export interface PlayResponse {
  plays: number;
}

export interface LikeUpdate {
  like: number;
}

export interface LikeResponse {
  like: number;
}

export interface AlbumDetailResponse {
  album: Album;
  tracks: Item[];
}

export interface TracksResponse {
  tracks: Item[];
  truncated?: boolean;
}

export interface SubtitlesResponse {
  subs: Subtitle[];
}

export interface KeyframeResponse {
  start: number;
}

export interface CropResponse {
  x?: number;
  y?: number;
  w?: number;
  h?: number;
  frameW?: number;
  frameH?: number;
}

export interface LinkRequest {
  target: string;
}

export interface LinkResponse {
  code: string;
  path: string;
}

export interface InfoResponse {
  thumbEpoch: string;
  content?: string[];
  streamToken?: string;
  confined?: boolean;
  build: Build;
  capabilities: Capabilities;
  streamExpires?: number;
}

export interface PrefsResponse {
  roots: string[];
  persisted: boolean;
  editable: boolean;
}

export interface PrefsUpdate {
  roots: string[];
}

export interface ConvertProgress {
  active: boolean;
  percent: number;
  kind?: string;
}

export interface PositionsResponse {
  positions: Record<string, Position>;
}

export interface PositionUpdate {
  t: number;
  d: number;
}

export interface FlagUpdate {
  ids?: string[];
  hidden?: boolean;
  favourite?: boolean;
  rotation?: number;
  nocrop?: boolean;
}

export interface FlagsResponse {
  flags: Record<string, Flags>;
}

export interface SpriteLayout {
  frames: number;
  cols: number;
  rows: number;
  frameWidth: number;
  minDurationMs: number;
}

export interface RendererInfo {
  id: string;
  name: string;
  volume?: boolean;
}

export interface RenderersResponse {
  renderers: RendererInfo[];
}

export interface CastStatus {
  state: string;
  position?: number;
  duration?: number;
  uri?: string;
}

export interface CastControl {
  action: string;
  seconds?: number;
  volume?: number;
}

export const SPRITE: SpriteLayout = {"frames":10,"cols":5,"rows":2,"frameWidth":320,"minDurationMs":30000};
